#include <arc/test/unit.h>


ARC_TEST(randomtest)
    ARC_ASSERT_TRUE(1)
    ARC_ASSERT_FALSE(0)
    ARC_ASSERT_INT_EQUAL(1, 1)
    ARC_ASSERT_ULONG_EQUAL(11832193802UL, 11832193802UL)
    ARC_ASSERT_STRING_EQUAL("HOLA", "HOLA")
    ARC_ASSERT_BIT_SET(4321, 0)
    ARC_ASSERT_BIT_NOT_SET(4320, 0)
    ARC_ASSERT_FLOAT_EQUAL(191.2F, 191.2F, 0.001F)
    ARC_ASSERT_DOUBLE_EQUAL(192.131, 192.131, 0.001)
    ARC_ASSERT_STRING_CONTAINS("HOLA", 'O')
    ARC_ASSERT_STRING_DOESNT_CONTAIN("HOLA", 'B')
    ARC_ASSERT_STRING_STARTS_WITH("HOLA", 'H')
    ARC_ASSERT_STRING_ENDS_WITH("HOLA", 'A')
ARC_END_TEST

ARC_TEST_FIXTURE
    ARC_ADD_TEST(randomtest)
ARC_END_TEST_FIXTURE

